name: FloorIsLava
version: 1.0
author: Arvind
main: me.arvind.FloorIsLava.Main
description: Lava rises 5 blocks every 60 seconds
commands:
  creepspawn:
    aliases: [fil]
    description: /fil to start game
